import { GoogleGenAI } from "@google/genai";

interface HotelContentRequest {
  hotelName: string;
  address: string;
  category: string;
  rating: number;
  reviews: Array<{
    author: string;
    text: string;
    rating: number;
    date: string;
  }>;
}

interface GeneratedHotelContent {
  headline: string;
  story: string;
  reviewSummary: string;
}

export class GeminiService {
  private ai: GoogleGenAI;

  constructor() {
    const apiKey = process.env.GEMINI_API_KEY || '';
    if (!apiKey) {
      throw new Error('Gemini API key is required');
    }
    this.ai = new GoogleGenAI({ apiKey });
  }

  async generateHotelContent(hotelData: HotelContentRequest): Promise<GeneratedHotelContent> {
    try {
      const systemPrompt = `You are an expert hotel marketing copywriter. Generate compelling marketing content for hotels that will attract guests and showcase the unique value proposition.

Your task is to create:
1. A catchy headline (max 60 characters) that captures the hotel's essence
2. A compelling "Our Story" section (2-3 paragraphs) that tells the hotel's narrative
3. A review summary (1 paragraph) that synthesizes guest feedback

Guidelines:
- Use an engaging, luxurious tone
- Highlight unique selling points
- Make content feel authentic and personal
- Focus on experiences and emotions
- Avoid generic hotel descriptions`;

      const prompt = `Generate marketing content for this hotel:

Hotel Name: ${hotelData.hotelName}
Location: ${hotelData.address}
Category: ${hotelData.category}
Rating: ${hotelData.rating}/5 stars

Guest Reviews:
${hotelData.reviews.map(review => 
  `- ${review.author} (${review.rating}/5): "${review.text}"`
).join('\n')}

Please respond with JSON in this exact format:
{
  "headline": "Your catchy headline here",
  "story": "Your multi-paragraph story here with proper line breaks",
  "reviewSummary": "Your review summary here"
}`;

      const response = await this.ai.models.generateContent({
        model: "gemini-2.5-pro",
        config: {
          systemInstruction: systemPrompt,
          responseMimeType: "application/json",
          responseSchema: {
            type: "object",
            properties: {
              headline: { type: "string" },
              story: { type: "string" },
              reviewSummary: { type: "string" },
            },
            required: ["headline", "story", "reviewSummary"],
          },
        },
        contents: prompt,
      });

      const rawJson = response.text;
      if (!rawJson) {
        throw new Error("Empty response from Gemini AI");
      }

      const generatedContent: GeneratedHotelContent = JSON.parse(rawJson);
      
      // Validate the generated content
      if (!generatedContent.headline || !generatedContent.story || !generatedContent.reviewSummary) {
        throw new Error("Incomplete content generated by AI");
      }

      return generatedContent;
    } catch (error) {
      console.error('Error generating hotel content with Gemini:', error);
      throw new Error(`Failed to generate hotel content: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }
}

export const geminiService = new GeminiService();
