import { GoogleGenAI } from "@google/genai";

interface HotelContentRequest {
  hotelName: string;
  address: string;
  category: string;
  rating: number;
  reviews: Array<{
    author: string;
    text: string;
    rating: number;
    date: string;
  }>;
}

interface GeneratedHotelContent {
  headline: string;
  story: string;
  reviewSummary: string;
}

export class GeminiService {
  private ai: GoogleGenAI;

  constructor() {
    const apiKey = process.env.GEMINI_API_KEY || '';
    if (!apiKey) {
      throw new Error('Gemini API key is required');
    }
    this.ai = new GoogleGenAI({ apiKey });
  }

  private async sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  async generateHotelContent(hotelData: HotelContentRequest): Promise<GeneratedHotelContent> {
    const maxRetries = 3;
    const baseDelay = 1000; // 1 second

    for (let attempt = 1; attempt <= maxRetries; attempt++) {
      try {
        const systemPrompt = `You are an expert hotel marketing copywriter. Generate compelling marketing content for hotels that will attract guests and showcase the unique value proposition.

Your task is to create:
1. A catchy headline (max 60 characters) that captures the hotel's essence
2. A compelling "Our Story" section (2-3 paragraphs) that tells the hotel's narrative
3. A review summary (1 paragraph) that synthesizes guest feedback

Guidelines:
- Use an engaging, luxurious tone
- Highlight unique selling points
- Make content feel authentic and personal
- Focus on experiences and emotions
- Avoid generic hotel descriptions`;

        const prompt = `Generate marketing content for this hotel:

Hotel Name: ${hotelData.hotelName}
Location: ${hotelData.address}
Category: ${hotelData.category}
Rating: ${hotelData.rating}/5 stars

Guest Reviews:
${hotelData.reviews.map(review => 
  `- ${review.author} (${review.rating}/5): "${review.text}"`
).join('\n')}

Please respond with JSON in this exact format:
{
  "headline": "Your catchy headline here",
  "story": "Your multi-paragraph story here with proper line breaks",
  "reviewSummary": "Your review summary here"
}`;

        console.log(`Attempting to generate hotel content (attempt ${attempt}/${maxRetries})`);
        
        const response = await this.ai.models.generateContent({
          model: "gemini-2.5-pro",
          config: {
            systemInstruction: systemPrompt,
            responseMimeType: "application/json",
            responseSchema: {
              type: "object",
              properties: {
                headline: { type: "string" },
                story: { type: "string" },
                reviewSummary: { type: "string" },
              },
              required: ["headline", "story", "reviewSummary"],
            },
          },
          contents: prompt,
        });

        const rawJson = response.text;
        if (!rawJson) {
          throw new Error("Empty response from Gemini AI");
        }

        const generatedContent: GeneratedHotelContent = JSON.parse(rawJson);
        
        // Validate the generated content
        if (!generatedContent.headline || !generatedContent.story || !generatedContent.reviewSummary) {
          throw new Error("Incomplete content generated by AI");
        }

        console.log(`Successfully generated hotel content on attempt ${attempt}`);
        return generatedContent;
        
      } catch (error: any) {
        console.error(`Error generating hotel content with Gemini (attempt ${attempt}/${maxRetries}):`, error);
        
        // Check if this is a retryable error (503 service unavailable)
        const isRetryableError = error?.status === 503 || 
                                error?.message?.includes('overloaded') ||
                                error?.message?.includes('503') ||
                                error?.message?.includes('UNAVAILABLE');
        
        if (isRetryableError && attempt < maxRetries) {
          const delay = baseDelay * Math.pow(2, attempt - 1); // Exponential backoff
          console.log(`Model is overloaded, retrying in ${delay}ms... (attempt ${attempt + 1}/${maxRetries})`);
          await this.sleep(delay);
          continue;
        }
        
        // If we've exhausted retries or it's not a retryable error
        if (attempt === maxRetries) {
          throw new Error(`Failed to generate hotel content after ${maxRetries} attempts: ${error instanceof Error ? error.message : 'Unknown error'}`);
        } else {
          throw new Error(`Failed to generate hotel content: ${error instanceof Error ? error.message : 'Unknown error'}`);
        }
      }
    }
    
    // This should never be reached due to the loop logic, but TypeScript requires it
    throw new Error('Unexpected error: Failed to generate hotel content');
  }
}

export const geminiService = new GeminiService();
